### ISSUE TITLE
Exceptions when used with aw sdk 101 (x86)

### ISSUE THREAD

**Issue by ViezeVingertjes** [Bloyteg/AW.SDK.Core#6]
When i use the 101 sdk instead of the 100, it will return an exception on one of the internal Instance methods after a few minutes have passed. Sounds like a GC problem, but i havent had the time to investigate any further and reverted to aw sdk 100.

**Comment by Mr-Byte** [comment]
Given that build 101 support is not supported and not guaranteed right now, I'll recommend that you continue to use build 100 until I can provide proper 101 support.
